package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the CachedEntityExample application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link CachedEntityExampleBO} 
 *
 * Cached Entity Example used for testing caching in rest client.
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.CachedEntityExampleBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class CachedEntityExampleMixIn extends CachedEntityExampleBaseMixIn { 
		
}
