package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the DefaultValueExample application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link DefaultValueExampleBO} 
 *
 * A simple domain entity with a generated id field, fields of different types, and default values assigned to many of its fields
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.DefaultValueExampleBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class DefaultValueExampleMixIn extends DefaultValueExampleBaseMixIn { 
		
}
