package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the ForeignKeyWithColumnDefinition application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link ForeignKeyWithColumnDefinitionBO} 
 *
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.ForeignKeyWithColumnDefinitionBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class ForeignKeyWithColumnDefinitionMixIn extends ForeignKeyWithColumnDefinitionBaseMixIn { 
		
}
