package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the IdentityKeyedEntity application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link IdentityKeyedEntityBO} 
 *
 * Entity that demonstrates uses of an IDENTITY as a generated value primary key
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.IdentityKeyedEntityBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class IdentityKeyedEntityMixIn extends IdentityKeyedEntityBaseMixIn { 
		
}
