package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the LocalTransientReferenceExample application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link LocalTransientReferenceExampleBO} 
 *
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.LocalTransientReferenceExampleBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class LocalTransientReferenceExampleMixIn extends LocalTransientReferenceExampleBaseMixIn { 
		
}
