package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the MappedSuperclassChildA application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link MappedSuperclassChildABO} 
 *
 * Child entity of MappedSuperclassParent demonstrating an inheritance hierarchy with a mapped superclass strategy
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.MappedSuperclassChildABaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class MappedSuperclassChildAMixIn extends MappedSuperclassChildABaseMixIn { 
		
}
