package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the NonUUIDKeyEntity application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link NonUUIDKeyEntityBO} 
 *
 * Entity that uses a non-generated value primary key
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.NonUUIDKeyEntityBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class NonUUIDKeyEntityMixIn extends NonUUIDKeyEntityBaseMixIn { 
		
}
