package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the SimpleDomainChild application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link SimpleDomainChildBO} 
 *
 * Child end of the 1-M relationship with SimpleDomain
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.SimpleDomainChildBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class SimpleDomainChildMixIn extends SimpleDomainChildBaseMixIn { 
		
}
