package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the TableNameMismatch application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link TableNameMismatchBO} 
 *
 * Entity that demonstrates an error when table names drift between src/main resources and metamodel instances
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.TableNameMismatchBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class TableNameMismatchMixIn extends TableNameMismatchBaseMixIn { 
		
}
