package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the UuidKeyedEntity application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link UuidKeyedEntityBO} 
 *
 * Entity that demonstrates uses a UUID as a generated value primary key
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json.UuidKeyedEntityBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class UuidKeyedEntityMixIn extends UuidKeyedEntityBaseMixIn { 
		
}
