package org.bitbucket.askllc.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the ValidationReferencedObject application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link ValidationReferencedObjectBO} 
 *
 * @see org.bitbucket.askllc.fermenter.cookbook.domain.bizobj.ValidationReferencedObjectBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class ValidationReferencedObjectMixIn extends ValidationReferencedObjectBaseMixIn { 
		
}
