package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the BeerExampleEntity application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link BeerExampleEntityBO} 
 *
 * Entity to help with the Getting Started Guide
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.BeerExampleEntityBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class BeerExampleEntityMixIn extends BeerExampleEntityBaseMixIn { 
		
}
