package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the ForeignKeyColumnCustomName application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link ForeignKeyColumnCustomNameBO} 
 *
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.ForeignKeyColumnCustomNameBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class ForeignKeyColumnCustomNameMixIn extends ForeignKeyColumnCustomNameBaseMixIn { 
		
}
