package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the GenerationTestEntity application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link GenerationTestEntityBO} 
 *
 * Entity to help with some generation edge cases
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.GenerationTestEntityBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class GenerationTestEntityMixIn extends GenerationTestEntityBaseMixIn { 
		
}
