package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the IntegerKeyedEntity application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link IntegerKeyedEntityBO} 
 *
 * Entity that demonstrates uses a integer as a generated value primary key
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.IntegerKeyedEntityBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class IntegerKeyedEntityMixIn extends IntegerKeyedEntityBaseMixIn { 
		
}
