package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the MappedSubclassB application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link MappedSubclassBBO} 
 *
 * Sub entity of MappedSuperclassParent demonstrating an inheritance hierarchy with a mapped superclass strategy
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.MappedSubclassBBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class MappedSubclassBMixIn extends MappedSubclassBBaseMixIn { 
		
}
