package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the SimpleDomainEagerChild application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link SimpleDomainEagerChildBO} 
 *
 * Eagerly fetched (by default) child end of the 1-M relationship with SimpleDomain
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.SimpleDomainEagerChildBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class SimpleDomainEagerChildMixIn extends SimpleDomainEagerChildBaseMixIn { 
		
}
