package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the StringKeyedEntity application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link StringKeyedEntityBO} 
 *
 * Entity that demonstrates using a string as a primary key
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.StringKeyedEntityBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class StringKeyedEntityMixIn extends StringKeyedEntityBaseMixIn { 
		
}
