package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the TransientFieldExample application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link TransientFieldExampleBO} 
 *
 * Entity that demonstrates the use of a transient field
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.TransientFieldExampleBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class TransientFieldExampleMixIn extends TransientFieldExampleBaseMixIn { 
		
}
