package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the TransientChildEntity application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link TransientChildEntityBO} 
 *
 * A non-persistent child entity
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.TransientChildEntityBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class TransientChildEntityMixIn extends TransientChildEntityBaseMixIn { 
		
}
