package org.technologybrewery.fermenter.cookbook.domain.transfer.json;

/**
 * Transfer object JSON contract for the TransientSubEntityExample application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link TransientSubEntityExampleBO} 
 *
 * A non-persistent entity
 * @see org.technologybrewery.fermenter.cookbook.domain.transfer.json.TransientSubEntityExampleBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class TransientSubEntityExampleMixIn extends TransientSubEntityExampleBaseMixIn { 
		
}
