package org.bitbucket.askllc.fermenter.cookbook.referencing.domain.transfer.json;

/**
 * Transfer object JSON contract for the LocalDomain application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link LocalDomainBO} 
 *
 * A local domain
 * @see org.bitbucket.askllc.fermenter.cookbook.referencing.domain.transfer.json.LocalDomainBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class LocalDomainMixIn extends LocalDomainBaseMixIn { 
		
}
