package org.bitbucket.askllc.fermenter.cookbook.referencing.domain.transfer.json;

/**
 * Transfer object JSON contract for the LocalDomainTransientReference application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link LocalDomainTransientReferenceBO} 
 *
 * A local persistent domain with external reference to transient entity
 * @see org.bitbucket.askllc.fermenter.cookbook.referencing.domain.transfer.json.LocalDomainTransientReferenceBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class LocalDomainTransientReferenceMixIn extends LocalDomainTransientReferenceBaseMixIn { 
		
}
