package org.technologybrewery.fermenter.cookbook.referencing.domain.transfer.json;

/**
 * Transfer object JSON contract for the LocalTransientDomain application entity.
 * 
 * Developers should insert any needed JSON serialization logic here for 
 * member variables or methods that are not automatically generated by 
 * Fermenter but defined directly in {@link LocalTransientDomainBO} 
 *
 * A non-persistent local domain entity with external reference to persistent and transient entities
 * @see org.technologybrewery.fermenter.cookbook.referencing.domain.transfer.json.LocalTransientDomainBaseMixIn
 *
 * GENERATED STUB CODE - PLEASE *DO* MODIFY
 *
 */
public abstract class LocalTransientDomainMixIn extends LocalTransientDomainBaseMixIn { 
		
}
